resources:
- manager.yaml
- credentials.yaml

patchesStrategicMerge:
- manager_pull_policy.yaml
- manager_credentials_patch.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: carp-controller
  newName: juanlee/carp-controller
  newTag: latest
